[package]
name = "dmux-host"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
crossterm = { workspace = true }
termwiz = { workspace = true }
libc = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
